version: '3.4'

services:
  currentaccount.api:
    image: ${DOCKER_REGISTRY-}currentaccountapi
    build:
      context: .
      dockerfile: CurrentAccount/CurrentAccount.API/Dockerfile
  currentaccount.transaction.api:
    image: ${DOCKER_REGISTRY-}currentaccounttransactionapi
    build:
      context: .
      dockerfile: Transaction/CurrentAccount.Transaction.API/Dockerfile
