version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  currentaccount.api:
    container_name: currentaccount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  currentaccount.transaction.api:
    container_name: currentaccount.transaction.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"