version: '3.4'

services:
  currentaccount.api:
    container_name: currentaccount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
  currentaccount.transaction.api:
    container_name: currentaccount.transaction.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"